name: Create release asset

on:
  release:
    types:
      - created

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  deploy:
    name: Create release asset
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        tools: composer
    - name: Install dependencies
      run: |
        npm install --silent
        composer install --no-dev
    - name: Run build steps
      run: |
        npm run build
        composer dump-autoload -o
    - name: Create deployment ZIP
      run: |
        mkdir -p lazy-loading-responsive-images
        rsync -rav --exclude-from='.rsync-exclude' --delete-excluded ./ lazy-loading-responsive-images
        zip -r lazy-loading-responsive-images.zip lazy-loading-responsive-images/
        rm -rf lazy-loading-responsive-images
    - name: Get Release
      id: get_release
      uses: bruceadams/get-release@v1.2.0
    - name: Upload ZIP to release.
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.get_release.outputs.upload_url }}
        asset_path: ./lazy-loading-responsive-images.zip
        asset_name: lazy-loading-responsive-images.zip
        asset_content_type: application/zip
